### ISSUE TITLE
Wrong file reference throws TypeError

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#177]
#### Describe the bug
When you try to reference a non-existing file on the top layer it correctly throws an error telling you the file does not exist. However when you reference a file which reference a non-existing file you get `Error: Cannot read property '$ref' of undefined`

#### How to Reproduce
This was found through the generator where I am using version `1.0.0-rc.11`.

Using the following AsyncAPI document:
```yaml
asyncapi: '2.0.0'
info:
  title: "API"
  version: '1.0.0'
defaultContentType: application/json
channels:
  questionaire/get:
    description: Get the newest version of the questionaire
    publish:
      message:
        $ref: 'some/correct/path/to/questionaire/message'
```
With a separated questionair message:
```yaml
name: QuestionaireMessage
payload:
  $ref: 'non-existing/path/to/schema'
```

Which throws the following exception:
```
Something went wrong:
Error: Cannot read property '$ref' of undefined
    at parse (/home/jtl/.nvm/versions/node/v12.14.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/parser.js:107:11)
```
The actual error being thrown are the following:
```
TypeError: Cannot read property '$ref' of undefined
    at findNode (/home/jtl/.nvm/versions/node/v12.14.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/utils.js:23:14)
    at findLocationOf (/home/jtl/.nvm/versions/node/v12.14.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/utils.js:52:12)
    at /home/jtl/.nvm/versions/node/v12.14.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/utils.js:227:28
    at Array.map (<anonymous>)
    at utils.findRefs (/home/jtl/.nvm/versions/node/v12.14.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/utils.js:227:17)
    at dereference (/home/jtl/.nvm/versions/node/v12.14.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/parser.js:153:13)
```

#### Expected behavior
If nested file reference are not located I expect it to throw an error which lets me know the file that cannot be found.
