### ISSUE TITLE
Nested additionProperties are never crawled and therefore not returned by allSchemas function

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#184]
#### Describe the bug
When you have two nested additionProperties without having the additionProperties under a property it is never crawled by the crawler and are never returned with `allSchemas()` function.

#### How to Reproduce
Given the following schema `O2` will never be returned by the `allSchemas()` function.
```
    type: object 
    x-parser-schema-id: O1
    additionalProperties:
         type: object 
         x-parser-schema-id: O2
         additionalProperties:
```

#### Expected behavior
Would expect the `allSchemas()` function to return `O2` as well.
