### ISSUE TITLE
Some schemas are never iterated

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#229]
### Describe the bug
The following schemas are never iterated and therefore are never assigned ids.
- Standalone component parameters 
- Standalone component traits with headers

### How to Reproduce
The following yaml file should give parameters and headers uids.
```yaml
asyncapi: 2.0.0
info:
  title: My API
  version: '1.0.0'
channels: {}
components:
  parameters:
    testParam:
      schema: 
        type: object
        properties:
          name:
            type: string
  messageTraits:
    extension:
      headers:
        type: object
        properties:
          some-common-header:
            type: string
```

### Expected behavior
Expected schemas to iterated

**Comment by jonaslagoni** [comment]
After some research here are the schemas keywords we need to add to the iterator:

- `patternProperties`
- `definitions`
- `dependencies`

Furthermore this check https://github.com/asyncapi/parser-js/blob/9efaeee7f8dbad2e8b3a2e1a793f178780009599/lib/iterators.js#L65 should be removed completely IMO. Since if properties have been defined (lets say they omit the `type` keyword) we still need to be able to iterate those properties.


Also this check https://github.com/asyncapi/parser-js/blob/9efaeee7f8dbad2e8b3a2e1a793f178780009599/lib/iterators.js#L60 needs to be done at each of the property/array keywords instead, so it should be moved to https://github.com/asyncapi/parser-js/blob/9efaeee7f8dbad2e8b3a2e1a793f178780009599/lib/iterators.js#L186 https://github.com/asyncapi/parser-js/blob/9efaeee7f8dbad2e8b3a2e1a793f178780009599/lib/iterators.js#L209 and wrap the code.

**Comment by jonaslagoni** [comment]
If anyone is up for the task we are always ready to help you out in the implementation of the issue, if it needs more explaining, just let us know 👋

**Comment by arjungarg07** [comment]
I am getting familiar with the codebase of parser-js and will pick up this issue real soon.

**Comment by arjungarg07** [comment]
Hey @jonaslagoni, By `standalone components` you mean which do not have `$ref` (reference) to another type of schemas?
Can you please clear this doubt on `standalone components` Thanks

**Comment by jonaslagoni** [comment]
@arjungarg07 Yes either that or directly referenced by the document such as for `testParam` is never referenced by a channel and therefore never given an id. Because it is a standalone parameter no one uses 😄 
```
asyncapi: 2.0.0
info:
  title: My API
  version: '1.0.0'
channels: {}
components:
  parameters:
    testParam:
      schema: 
        type: object
        properties:
          name:
            type: string
```
Did that make sense? 🤔

**Comment by arjungarg07** [comment]
Yeah, that makes sense. Thanks😀

**Comment by arjungarg07** [comment]
Hey @jonaslagoni , I parsed this doc, and on calling `doc.allSchemas()` I am getting the output as shown. I think `patternProperties` ,`definitions`, `dependencies` are already iteratable, So can you please tell why do we need to add these keywords in iterator?
```
asyncapi: 2.0.0
info:
  title: My API
  version: '1.0.0'
channels: {}
components:
  parameters:
    testParam:
      schema: 
        type: object
        properties:
          name:
            type: string
  messageTraits:
    extension:
      headers:
        type: object
        properties:
          some-common-header:
            type: string
  schemas: 
    dependencies:
      test: ['test']
    patternProperties:
      test:
        type: string
    definitions: 
      test: 
        type: string
```
<img width="465" alt="Screenshot 2021-03-30 at 3 10 40 PM" src="https://user-images.githubusercontent.com/53009722/112968620-19c78880-916a-11eb-927e-a3ac56b66f56.png">

**Comment by jonaslagoni** [comment]
@arjungarg07  In your example you have defined schemas called `patternProperties` ,`definitions` and `dependencies`. You need to use them as keywords in a schema. Such as:

```yaml
{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "credit_card": { "type": "number" },
    "billing_address": { "$ref": "#/definitions/address" }
  },
  "required": ["name"],
  "dependencies": {
    "credit_card": {
      "properties": {
        "billing_address_2": { "type": "string" }
      },
      "required": ["billing_address_2"]
    }
  }
  "patternProperties": {
    "^S_": { "type": "string" },
    "^I_": { "type": "integer" }
  },
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  }
}
```
