### ISSUE TITLE
MIssing validation of channel parameters

### ISSUE THREAD

**Issue by jdall** [asyncapi/parser-js#24]
It would be nice if the parser could validate channel parameters
Having e.g.
```
channels
  playground/testParams/{param1}
```   
without the parameters being specified like e.g.
```
    parameters:
      - name: param1
        schema:
          type: string
```
should result in the parser bailing out - with a useful error message.
Please consider this.
Thanks.

**Comment by fmvilas** [comment]
Absolutely agree. Side note: take into account that new syntax for parameters is going to be like this:

```yaml
channels:
  playground/testParams/{param1}:
    parameters:
      param1:
        schema:
          type: string
```

Parameters is now a map instead of an array.
