### ISSUE TITLE
Unknown schemaFormat throws code error

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#303]
#### Describe the bug
We assume that parser exists for custom schema format when it might. This throws `PARSERS[String(...)] is not a function` which is not really saying anything.

#### How to Reproduce
I just used the playground with the following schema:

```yml
asyncapi: 2.0.0
id: urn:com.asyncapi.examples.user
info:
  title: User service
  version: 1.6.3
channels:
  user/signedup:
    publish:
      message:
        schemaFormat: 'application/cloudevents+json; version=0.2; charset=utf-8'
        payload:
          type: object
          properties:
            fullName:
              type: string
            email:
              type: string
              format: email
```

#### Expected behavior
Expected it to throw a meaningful error.

Fault location: https://github.com/asyncapi/parser-js/blob/c9d751ce3e5591f0b506db2a84b5dc6dff080f11/lib/parser.js#L193
