### ISSUE TITLE
References are bundled before validated

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#405]
#### Describe the bug
Currently, the parser bundles any references together with the provided AsyncAPI document before it's validated against the [JSON Schema document for AsyncAPI](https://github.com/asyncapi/spec-json-schemas/blob/master/schemas/2.2.0.json).

This results in invalid AsyncAPI documents being valid.

#### How to Reproduce
Given the following AsyncAPI document: 
```yaml
asyncapi: '2.2.0'
info:
  title: Test overriding dereferenced objects 
  version: '1.0.0'
servers:
  test:
    $ref: 'testServer.yaml'
```
Together with the server file:
```yaml
url: ws://mycompany.com/ws
protocol: ws
```

The parser accepts the AsyncAPI document as being valid because we bundle the reference together with the document, before it is validated.

The spec however does not allow that servers to be referenced: https://www.asyncapi.com/docs/specifications/v2.2.0#serversObject

NOTE: You cannot try this in the studio because it automatically validates beyond what the parser does, so the studio catches such mistakes.
