### ISSUE TITLE
AsyncAPI reference to Avro [BUG] 

### ISSUE THREAD

**Issue by sckrecords** [asyncapi/parser-js#46]
**Describe the bug**
I try to make a reference to an Avro object in AsyncAPI. For development, I used playground.asyncapi.io.
When defining a reference to our Kafka Schema Registry, which returns Avro like in your documentation

```
"Train": {
  "name": "Train",
  "title": "Train Information",
  "summary": "Inform about Trains.",
  "schemaFormat": "application/vnd.apache.avro+json;version=1.9.0",
  "payload": {
    "$ref": "https://schema-registry-dev.app.01d.io.sbb.ch/subjects/kafka.my-schema-value/versions/1#Train"
  }
}
```

the reference gets correctly resolved to

```
"Train": {
  "name": "Train",
  "title": "Train Information",
  "summary": "Information about trains.",
  "payload": {
    "subject": "kafka.my-schema-value",
    "version": 1,
    "id": 1,
    "schema":   
        {
          "type": "record",
          "name": "Train",
          "namespace": "ch.sbb.kafka.platform.model",
          "fields": [
            {
              "name": "model",
              "type": "string"
            },
            {
              "name": "manufacturer",
              "type": "string"
            }
          ]
        }
    }
}
```

this means that the reference itself and the link is working correctly. But when you then check the HTML panel in playground, the payload object is displayed as "", instead of the object. Do I miss something here or is the playground component broken?

**To Reproduce**
1. Open playground.asyncapi.io
2. Enter an AsyncAPI document with a reference to Avro as described above.
3. The reference gets resolved automatically.
4. Check right HTML panel for the operation that included the reference. Payload is "" instead of the object.

**Expected behavior**
Object is being displayed in JSON.

**Screenshots**
I have a screenshot. How do I add it to this bug report?

**Comment by sckrecords** [comment]
Here it is how it looks like in playground GUI:
![Avro in AsyncAPI GUI](https://user-images.githubusercontent.com/32662867/76395689-308d1880-6378-11ea-9aa3-459af2d0ba5f.png)

Here is the Doc. The Avro is in the "train" message:
[AsyncAPI_with_Avro.json.txt](https://github.com/asyncapi/parser-js/files/4316825/AsyncAPI_with_Avro.json.txt)

**Comment by derberg** [comment]
@sckrecords awesome input, thanks a lot. As you can see in attached asyncapi doc, the `Train` is not transformed into a valid json schema, and this is why it is later not rendered properly in the HTML. Avro -> JSON Schema transformation is not yet supported in the parser

**Comment by sckrecords** [comment]
When can we expect Avro -> JSON Schema transformation in parser? :-)

**Comment by derberg** [comment]
excellent question 😄 
it all depends on how important it is for the community and if someone experience can also help with contribution.

Good think is that we just recently introduced `plugins-like` approach for custom schema parsers. You can see for example the RAML parser here https://github.com/asyncapi/raml-dt-schema-parser that can be developed independently from the parser-js.

**Comment by sckrecords** [comment]
This one should be fixed within the other bunch of issues regarding AsyncAPI Reatct component, shouldn't it?

**Comment by derberg** [comment]
@sckrecords what do you mean? Avro support is not needed only in the react component. Avro schema parser can be useful for anyone, we will for example for sure register it by default in the generator

**Comment by derberg** [comment]
@fmvilas this issue is declared as in scope for parser 1.0 but Avro support is not `much have` in my opinion, especially that it is going to be a separate project anyway like in case of raml and openapi parsers

**Comment by fmvilas** [comment]
Agree. Feel free to exclude it from v1.0 release.

**Comment by derberg** [comment]
Just to make it clear for others watching this issue, we are not dropping the idea of supporting Avro, we just want to focus on bugs and missing validation features for the 1.0 release and Avro will just come after

**Comment by fmvilas** [comment]
I'm starting to work on this issue now.

**Comment by fmvilas** [comment]
I just updated [playground.asyncapi.io]() to have support for Avro schemas. Feel free to try it!

Example document:

```yaml
asyncapi: 2.0.0
info:
  title: Example with Avro
  version: 0.1.0
channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload: # The following is an Avro schema in YAML format (JSON format is also supported)
          type: record
          doc: User information
          fields:
            - name: displayName
              type: string
            - name: email
              type: string
            - name: age
              type: int
```

This is the package doing the magic: [github.com/asyncapi/avro-schema-parser]().

I'm closing this issue but feel free to open new ones on the [Avro Schema Parser](github.com/asyncapi/avro-schema-parser) repo.
