### ISSUE TITLE
message examples invalid against avro payload

### ISSUE THREAD

**Issue by chrispatmore** [asyncapi/parser-js#772]
#### Describe the bug
When supplying an avro payload for a message, and supplying examples that match that payload the examples cause a validation error:
```
schema is invalid: data/type must be equal to one of the allowed values, data/type must be array, data/type must match a schema in anyOf
```
- If I comment out the examples the async api validates correctly and generates an example that looks exactly like the one supplied. 
- If I comment out the payload and leave the examples the async api validates correctly
- If I switch the avro payload to a json payload everything validates correctly 

#### How to Reproduce
Use this example api:
```yaml
asyncapi: 2.6.0
info:
  description: Orders which have been placed on our webstore
  title: Orders
  version: 1.0.0
tags:
  - name: Webstore
  - name: Product
channels:
  Orders:
    subscribe:
      message:
        schemaFormat: "application/vnd.apache.avro;version=1.9.0"
        payload: {"type":"record","name":"WindRecordings","fields":[{"name":"direction","type":{"type":"enum","name":"directionEnum","symbols":["North","East","South","West"]}},{"name":"speed","type":"string"}]}
        examples: [
          {
            payload: {
              "direction": "North",
              "speed": "18"
            }
          }
        ]
```

<img width="789" alt="Screenshot 2023-05-17 at 14 01 40" src="https://github.com/asyncapi/parser-js/assets/25282447/7c6996d1-54a7-45d9-84e7-a132d5787a35">

#### Expected behaviour
I would expect that the parser would validate the examples against the avro schema and my async api would be valid.

#### Notes
I tried to look through the code to find where the issue was coming from, and my best guess is that https://github.com/asyncapi/parser-js/blob/20be09d64077d4933cc093cf3d5d87d4ea17d99c/src/ruleset/v2/functions/messageExamples.ts#L79 is not taking into consideration that the schema may be avro. Given that this may actually be a feature request, or I may be completely wrong
